# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['LustreSeparator.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('index.html', '.'),
        ('styles.css', '.'),
        ('web_app.js', '.'),
        ('app.js', '.'),
        ('version.json', '.'),
        ('logo.png', '.'),
        ('logo.ico', '.'),
        ('favicon.ico', '.'),
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'webview',
        'clr_loader',
        'pythonnet',
        'http.server',
        'urllib.request',
        'json',
        'threading',
        'auto_updater',
        'web_server',
        'local_video_seo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Lustre Separator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='logo.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
